name: Deployment (Full Release)

permissions:
  contents: write

on:
  release:
    types:
      - published

jobs:
  pull_request:
    name: Deploy Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@v4

      - name: Build executable
        run: |
          mkdir -p dist
          echo 'testing' > dist/raspycam

      - name: Clone forked frontend repository
        env:
          FORKED_REPO_URL: ${{ secrets.FORKED_REPO_URL }}
        run: |
          git clone $FORKED_REPO_URL rpi_cam_web_interface
          cd rpi_cam_web_interface
          git checkout -b update-raspycam-${{ github.event.release.tag_name }}

      - name: Ensure directory exists in target
        run: |
          mkdir -p rpi_cam_web_interface/etc/raspycam

      - name: Transfer executable to forked repository
        run: |
          cp dist/raspycam rpi_cam_web_interface/etc/raspycam/

      - name: Stage, Commit, and Push Changes
        env:
          PAT: ${{ secrets.PAT }}
          FORKED_REPO_URL: ${{ secrets.FORKED_REPO_URL }}
        run: |
          cd rpi_cam_web_interface
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add etc/raspycam/raspycam
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Updating RasPyCam to ${{ github.event.release.tag_name }}"
            git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/kaihokori/rpi_cam_web_interface.git
            git push origin update-raspycam-${{ github.event.release.tag_name }}
          fi

      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y gh

      - name: Fetch Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_URL="https://api.github.com/repos/kaihokori/raspycam/releases/tags/${{ github.event.release.tag_name }}"
          curl -s -H "Authorization: token $GITHUB_TOKEN" $RELEASE_URL | jq -r '.body' > release_notes.txt

      - name: Create Draft Pull Request
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          gh auth login --with-token <<< "${{ secrets.PAT }}"
          gh pr create --title "Update RasPyCam to ${{ github.event.release.tag_name }}" --body "# Release Summary\n\nThis PR updates the RasPyCam executable to the latest version \`${{ github.event.release.tag_name }}\`, generated from the [RasPyMJPEG](https://github.com/kaihokori/raspycam) repository.\n\n## Changes Introduced\n\n1. **Change 1:**\n   - Content 1\n\n2. **Change 2:**\n   - Content 2\n\n## Testing & Validation\n\n> [!NOTE]\n> This section will not be included in future releases. This section is only included for the initial release to provide context on the testing process.\n\nThe following tests have been performed to validate this update:\n\n- **Manual Tests:**\n  - The updated RasPyCam executable has been tested on a Raspberry Pi device both in standalone mode and in conjunction with the RPi_Cam_Web_Interface. The executable has been verified to be working as expected.\n  \n- **Automated Testing:**\n  - Unit tests have been run to ensure that individual components of the executable are functioning correctly. All tests have passed successfully.\n  - Integration tests have been run to ensure that the executable integrates seamlessly with the RPi_Cam_Web_Interface. All tests have passed successfully.\n  - End-to-end tests have been run to ensure that the executable performs as expected in a real-world scenario. All tests have passed successfully.\n\n## Additional Notes\n\n- **Automation:** This pull request was generated as part of an automated process. Similar draft pull requests will be automatically created for each new release of RasPyCam. Note that the draft pull request will continue to be manually reviewed before changing the status to \`Ready for Review\`.\n- **Future Changes:** Please feel free to suggest improvements to the automation or deployment process if there are areas that can be streamlined for easier integration with the RPi_Cam_Web_Interface repository.\n\n## Changelog\n\nFor a detailed list of changes and improvements, refer to the official release notes of RasPyCam version \`${{ github.event.release.tag_name }}\`:\n\n\`\`\`\n$(cat release_notes.txt)\n\`\`\`\n" --base main --head "kaihokori:update-raspycam-${{ github.event.release.tag_name }}" --repo traitsaponin/rpi_cam_web_interface --draft

      - name: Clean up
        run: |
          rm -rf ./rpi_cam_web_interface release_notes.txt dist
