name: Deployment (Full Release)

permissions:
  contents: write

on:
  release:
    types:
      - published

jobs:
  pull_request:
    name: Deploy Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@v4

      - name: Download executable from release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the latest release
          release_response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/kaihokori/raspycam/releases/latest)
          
          # Extract the download URL for the asset (raspycam)
          asset_url=$(echo "$release_response" | jq -r '.assets[] | select(.name == "raspycam") | .browser_download_url')
          
          # Download the asset (raspycam executable)
          curl -L -o raspycam -H "Authorization: token $GITHUB_TOKEN" "$asset_url"
          
          # Make the file executable
          chmod +x raspycam

      - name: Clone forked frontend repository
        env:
          FORKED_REPO_URL: ${{ secrets.FORKED_REPO_URL }}
        run: |
          git clone $FORKED_REPO_URL rpi_cam_web_interface
          cd rpi_cam_web_interface

      - name: Add upstream repository and fetch latest changes
        run: |
          git remote add upstream https://github.com/traitsaponin/rpi_cam_web_interface.git
          git fetch upstream
          git checkout main
          git merge upstream/main

      - name: Create new branch for update
        run: |
          git checkout -b update-raspycam-${{ github.event.release.tag_name }}

      - name: Ensure directory exists in target
        run: |
          mkdir -p rpi_cam_web_interface/etc/raspycam

      - name: Transfer executable to forked repository
        run: |
          cp raspycam rpi_cam_web_interface/etc/raspycam/

      - name: Stage, Commit, and Push Changes
        env:
          PAT: ${{ secrets.PAT }}
          FORKED_REPO_URL: ${{ secrets.FORKED_REPO_URL }}
        run: |
          cd rpi_cam_web_interface
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add etc/raspycam/raspycam
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Updating RasPyCam to ${{ github.event.release.tag_name }}"
            git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/kaihokori/rpi_cam_web_interface.git
            
            git branch -M update-raspycam-${{ github.event.release.tag_name }}
            
            git push --set-upstream origin update-raspycam-${{ github.event.release.tag_name }}
          fi

      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y gh

      - name: Fetch Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_URL="https://api.github.com/repos/kaihokori/raspycam/releases/tags/${{ github.event.release.tag_name }}"
          curl -s -H "Authorization: token $GITHUB_TOKEN" $RELEASE_URL | jq -r '.body' > release_notes.txt

      - name: Create PR body file
        run: |
          echo "# Release Summary" > pr_body.txt
          echo "" >> pr_body.txt
          echo "This PR updates the RasPyCam executable to the latest version \`${{ github.event.release.tag_name }}\`, generated from the [RasPyCam](https://github.com/kaihokori/raspycam) repository." >> pr_body.txt
          echo "" >> pr_body.txt
          echo "## Changes Introduced" >> pr_body.txt
          echo "" >> pr_body.txt
          echo "1. **Change X:**" >> pr_body.txt
          echo "   - [Text]" >> pr_body.txt
          echo "" >> pr_body.txt
          echo "## Additional Notes" >> pr_body.txt
          echo "" >> pr_body.txt
          echo "- **Manual Usage:**: If you want to test the application manually, please follow the instructions provided in the [RasPyCam](https://github.com/kaihokori/raspycam) README." >> pr_body.txt
          echo "" >> pr_body.txt
          echo "## Changelog" >> pr_body.txt
          echo "" >> pr_body.txt
          echo "The following is copied from the \`${{ github.event.release.tag_name }}\` release notes for the [RasPyCam](https://github.com/kaihokori/raspycam) application:" >> pr_body.txt
          echo "" >> pr_body.txt
          echo "" >> pr_body.txt
          cat release_notes.txt >> pr_body.txt
          echo "" >> pr_body.txt

      - name: Create Draft Pull Request
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          gh auth login --with-token <<< "${{ secrets.PAT }}"
          gh pr create --title "Update RasPyCam to ${{ github.event.release.tag_name }}" --body-file pr_body.txt --base main --head "kaihokori:update-raspycam-${{ github.event.release.tag_name }}" --repo traitsaponin/rpi_cam_web_interface --draft

      - name: Clean up
        run: |
          rm -rf ./rpi_cam_web_interface release_notes.txt raspycam pr_body.txt
