name: Deployment (Full Release)

permissions:
  contents: write

on:
  release:
    types:
      - published

jobs:
  pull_request:
    name: Deploy Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@v4

      - name: Build executable
        run: |
          mkdir -p dist
          echo 'testing' > dist/raspycam

      - name: Clone forked frontend repository
        env:
          FORKED_REPO_URL: ${{ secrets.FORKED_REPO_URL }}
        run: |
          git clone $FORKED_REPO_URL rpi_cam_web_interface
          cd rpi_cam_web_interface
          git checkout -b update-raspycam-${{ github.event.release.tag_name }}

      - name: Ensure directory exists in target
        run: |
          mkdir -p rpi_cam_web_interface/etc/raspycam

      - name: Transfer executable to forked repository
        run: |
          cp dist/raspycam rpi_cam_web_interface/etc/raspycam/

      - name: Stage, Commit, and Push Changes
        env:
          PAT: ${{ secrets.PAT }}
          FORKED_REPO_URL: ${{ secrets.FORKED_REPO_URL }}
        run: |
          cd rpi_cam_web_interface
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add etc/raspycam/raspycam
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Updating RasPyCam to ${{ github.event.release.tag_name }}"
            git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/kaihokori/rpi_cam_web_interface.git
            git push origin update-raspycam-${{ github.event.release.tag_name }}
          fi

      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y gh

      - name: Fetch Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_URL="https://api.github.com/repos/kaihokori/raspycam/releases/tags/${{ github.event.release.tag_name }}"
          curl -s -H "Authorization: token $GITHUB_TOKEN" $RELEASE_URL | jq -r '.body' > release_notes.txt

      - name: Create Draft Pull Request
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          gh auth login --with-token <<< "${{ secrets.PAT }}"
          gh pr create --title "Update RasPyCam to ${{ github.event.release.tag_name }}" --body "
### Pull Request Overview

**Title:** Update RasPyCam to \`${{ github.event.release.tag_name }}\`  
**Description:** This PR updates the RasPyCam executable to the latest version \`${{ github.event.release.tag_name }}\`, generated from the [RasPyMJPEG](https://github.com/kaihokori/raspycam) repository.

---

### Release Summary

- **Version:** \`${{ github.event.release.tag_name }}\`
- **Release Date:** \`${{ github.event.release.created_at }}\`
- **Description:**
  - {{ github.event.release.name }}

---

### Changes Introduced

1. **Updated RasPyCam executable:**
   - Replaced the existing RasPyCam executable with the new version located at \`etc/raspycam/raspycam\`.
   - Ensure compatibility with the existing RPi_Cam_Web_Interface.

2. **Directory Updates:**
   - Verified that the directory \`etc/raspycam/\` exists or created it as needed.
   - Transferred the new executable to this directory.

3. **Commit Message:**
   - Commit message: \`Updating RasPyCam to \${{ github.event.release.tag_name }}\`

---

### Testing & Validation

The following tests have been performed to validate this update:

- **Build Tests:**
  - Confirmed the successful build of the RasPyCam executable on Ubuntu (latest).
  
- **Deployment Testing:**
  - Ensured proper placement of the executable in the target directory within the \`rpi_cam_web_interface\` repository.
  
- **Functional Testing:**
  - (If applicable) Outline any functional tests or performance checks that have been done to ensure the new executable works as expected.

---

### Additional Notes

- **Automation:** This workflow is part of an automated process. Pull requests like this one will be generated automatically for each new release of RasPyCam.  
- **Future Changes:** Please feel free to suggest improvements to the automation or deployment process if there are areas that can be streamlined for easier integration with the RPi_Cam_Web_Interface.

---

### Related Links

- [RasPyMJPEG Release Notes](https://github.com/kaihokori/raspycam/releases/tag/\${{ github.event.release.tag_name }})
- [RasPyMJPEG Repository](https://github.com/kaihokori/raspycam)
- [RPi_Cam_Web_Interface](https://github.com/traitsaponin/rpi_cam_web_interface)

---

### Reviewer Instructions

To merge this PR:
1. Verify the changes made to the \`rpi_cam_web_interface\` repository, particularly the new RasPyCam executable.
2. Run any necessary tests to ensure proper integration with the web interface.
3. Once verified, merge the PR into the main branch.

---

### Changelog

For a detailed list of changes and improvements, refer to the official release notes of RasPyCam version \`${{ github.event.release.tag_name }}\`:

\`\`\`
$(cat release_notes.txt)
\`\`\`

          " --base main --head "kaihokori:update-raspycam-${{ github.event.release.tag_name }}" --repo traitsaponin/rpi_cam_web_interface --draft

      - name: Clean up
        run: |
          rm -rf ./rpi_cam_web_interface release_notes.txt dist