name: Deployment

permissions:
  contents: write

on:
  push:
    branches:
      - '**'

jobs:
  release:
    name: Full Release Job
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@v4

      # Get the latest tag and fetch all tags to ensure we are working with the latest
      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          # Get the latest tag (sort by version number)
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      # Bump the version, incrementing based on the latest tag
      - name: Bump version
        id: bump_version
        run: |
          if [ -z "${{ env.LATEST_TAG }}" ]; then
            # If no tag exists, start with v1
            echo "v1" > new_tag
          else
            # Extract the numeric part of the latest tag
            version_number=$(echo "${{ env.LATEST_TAG }}" | grep -o '[0-9]*$')
            # Increment the version number
            new_version=$((version_number+1))
            echo "Bumping version to v$new_version"
            echo "v$new_version" > new_tag
          fi
          echo "NEW_TAG=$(cat new_tag)" >> $GITHUB_ENV

      # Create a new tag if it doesn't exist yet
      - name: Create new tag
        run: |
          new_tag=$(cat new_tag)
          if git rev-parse "refs/tags/$new_tag" >/dev/null 2>&1; then
            echo "Tag $new_tag already exists. Skipping tag creation."
          else
            echo "Creating new tag: $new_tag"
            git tag $new_tag
            git push origin $new_tag
          fi

      # Simulate building executable
      - name: Simulate building executable
        run: |
          mkdir -p dist
          touch dist/raspymjpeg

      - name: Automatically Generate GitHub Release with Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/kaihokori/raspymjpeg/releases \
            -d '{
              "tag_name": "'${{ env.NEW_TAG }}'",
              "name": "Release '${{ env.NEW_TAG }}'",
              "prerelease": false,
              "draft": false,
              "generate_release_notes": true
            }'

      - name: Clone forked frontend repository
        env:
          FORKED_REPO_URL: ${{ secrets.FORKED_REPO_URL }}
        run: |
          git clone $FORKED_REPO_URL rpi_cam_web_interface
          cd rpi_cam_web_interface
          git checkout -b update-raspymjpeg-${{ env.NEW_TAG }}

      - name: Ensure directory exists in target
        run: |
          mkdir -p rpi_cam_web_interface/etc/raspymjpeg

      - name: Transfer executable to forked repository
        run: |
          cp dist/raspymjpeg rpi_cam_web_interface/etc/raspymjpeg/

      - name: Stage and Commit Changes
        run: |
          cd rpi_cam_web_interface
          git add etc/raspymjpeg/raspymjpeg
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Updating RasPyMJPEG to ${{ env.NEW_TAG }}"
          fi

      - name: Push changes to fork
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          cd rpi_cam_web_interface
          git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository_owner }}/rpi_cam_web_interface.git update-raspymjpeg-${{ env.NEW_TAG }}

      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y gh

      - name: Fetch Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_URL="https://api.github.com/repos/kaihokori/raspymjpeg/releases/tags/${{ env.NEW_TAG }}"
          curl -s -H "Authorization: token $GITHUB_TOKEN" $RELEASE_URL | jq -r '.body' > release_notes.txt

      - name: Create Pull Request
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          gh auth login --with-token <<< "${{ secrets.PAT }}"
          # Validate branch before creating the PR
          if git rev-parse --verify update-raspymjpeg-${{ env.NEW_TAG }} >/dev/null 2>&1; then
            gh pr create --title "Update RasPyMJPEG to ${{ env.NEW_TAG }}" --body "$(cat release_notes.txt)" --base main --head update-raspymjpeg-${{ env.NEW_TAG }}
          else
            echo "Branch not found. Aborting PR creation."
          fi

      - name: Clean up after release
        run: |
          rm -rf ./release ./rpi_cam_web_interface
