name: Deployment (Partial Release)

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release-arm64:
    name: Partial Release ARM64
    runs-on: ARM64
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@v4

      - name: Clear Git cache
        run: |
          git rm -r --cached .
          git reset --hard

      - name: Delete all draft releases and their tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          releases=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/kaihokori/raspycam/releases \
            | jq -r '.[] | select(.draft == true) | .id,.tag_name')
          if [ -n "$releases" ]; then
            echo "$releases" | while read -r release_id && read -r tag_name; do
              echo "Deleting draft release with tag: $tag_name (ID: $release_id)"
              curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/kaihokori/raspycam/releases/$release_id
              git tag -d "$tag_name" || true
              git push origin --delete "$tag_name" || true
            done
          else
            echo "No draft releases found."
          fi

      - name: Delete tags without releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --tags
          all_tags=$(git tag)
          release_tags=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/kaihokori/raspycam/releases \
            | jq -r '.[].tag_name')
          echo "$all_tags" | while read -r tag; do
            if ! echo "$release_tags" | grep -q "$tag"; then
              echo "Deleting tag: $tag (no associated release)"
              git tag -d "$tag" || true
              git push origin --delete "$tag" || true
            fi
          done

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Bump version
        id: bump_version
        run: |
          if [ -z "${{ env.LATEST_TAG }}" ]; then
            echo "v1" > new_tag
          else
            version_number=$(echo "${{ env.LATEST_TAG }}" | grep -o '[0-9]*$')
            new_version=$((version_number+1))
            echo "v$new_version" > new_tag
          fi
          echo "NEW_TAG=$(cat new_tag)" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          new_tag=$(cat new_tag)
          if git rev-parse "refs/tags/$new_tag" >/dev/null 2>&1; then
            echo "Tag $new_tag already exists. Skipping tag creation."
          else
            git tag $new_tag
            git push origin $new_tag
          fi

      - name: Set up dependencies and build executable
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install wheel rpi-libcamera rpi-kms picamera2 numpy Pillow opencv-python pyinstaller
          pyinstaller raspycam.spec --noconfirm
          mv dist/raspycam dist/RasPyCam-ARM64

      - name: Archive build artifacts
        run: |
          mkdir -p release
          tar -czvf release/RasPyCam-ARM64.tar.gz -C dist RasPyCam-ARM64

      - name: Generate GitHub draft release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/kaihokori/raspycam/releases \
            -d '{
              "tag_name": "'${{ env.NEW_TAG }}'",
              "name": "Release '${{ env.NEW_TAG }}'",
              "prerelease": false,
              "draft": true,
              "generate_release_notes": true
            }')
          echo "$response" | jq -r '.upload_url' | sed 's/{?name,label}//' > upload_url.txt

      - name: Upload executable to GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          upload_url=$(cat upload_url.txt)
          curl -s --data-binary @release/RasPyCam-ARM64.tar.gz \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            "$upload_url?name=RasPyCam-ARM64.tar.gz"

      - name: Save upload URL and new tag as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-info
          path: |
            upload_url.txt
          retention-days: 1

      - name: Cleanup build artifacts
        run: |
          rm -rf venv dist release upload_url.txt new_tag

  release-x64:
    name: Partial Release X64
    runs-on: ARM64  # This should be changed to 'X64' when the X64-based Pi is set up as a self-hosted runner
    needs: release-arm64
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@v4

      - name: Download release information
        uses: actions/download-artifact@v3
        with:
          name: release-info
          path: ./release-info
          
      - name: Set up dependencies and build executable
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install wheel rpi-libcamera rpi-kms picamera2 numpy Pillow opencv-python pyinstaller
          pyinstaller raspycam.spec --noconfirm
          mv dist/raspycam dist/RasPyCam-X64

      - name: Archive build artifacts
        run: |
          mkdir -p release
          tar -czvf release/RasPyCam-X64.tar.gz -C dist RasPyCam-X64

      - name: Upload executable to GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          upload_url=$(cat release-info/upload_url.txt)
          curl -s --data-binary @release/RasPyCam-X64.tar.gz \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            "$upload_url?name=RasPyCam-X64.tar.gz"

      - name: Cleanup build artifacts
        run: |
          rm -rf venv dist release release-info
