name: Integration

permissions:
  contents: write

on:
  push:
    branches:
      - '**'

jobs:
  check-runners:
    if: github.event_name == 'push'
    name: Check Runners
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: |
          echo "Placeholder"

  format:
    if: github.event_name == 'push'
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: |
          echo "Placeholder"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Placeholder
        run: |
          echo "Placeholder"

  test-five:
    name: Test (Pi 5)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Placeholder
        run: |
          echo "Placeholder"

  test-four:
    name: Test (Pi 4)
    runs-on: ubuntu-latest
    needs: [lint, check-runners]
    steps:
      - name: Placeholder
        run: |
          echo "Placeholder"

  test-three-b:
    name: Test (Pi 3B)
    runs-on: ubuntu-latest
    needs: [lint, check-runners]
    steps:
      - name: Placeholder
        run: |
          echo "Placeholder"

  test-two-w:
    name: Test (Pi Zero 2W)
    runs-on: ubuntu-latest
    needs: [lint, check-runners]
    steps:
      - name: Placeholder
        run: |
          echo "Placeholder"