name: Integration (Coverage)

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  coverage:
    name: Coverage Report
    runs-on: self-hosted
    steps:
      - name: Placeholder
        run: |
          echo "Placeholder"
